/* MTI_DPI */

/*
 * Copyright 2002-2013 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'win32pe'
 */
#ifndef INCLUDED_DPIHEADER
#define INCLUDED_DPIHEADER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
py_end();

DPI_LINK_DECL DPI_DLLESPEC
int
py_exe(
    int a,
    int* o);

DPI_LINK_DECL DPI_DLLESPEC
int
py_func(
    const char* func_name);

DPI_LINK_DECL DPI_DLLESPEC
int
py_start(
    double time_step,
    int divide_num);

DPI_LINK_DECL int
v_task(
    int i,
    int* o);

#endif 
